import { ExecutionRunTrace } from "@/lib/execution-trace";

const base = new Date("2026-03-13T10:25:00.000Z").getTime();

function at(offsetMs: number): string {
  return new Date(base + offsetMs).toISOString();
}

function log(id: string, offsetMs: number, level: "debug" | "info" | "warn" | "error", message: string, source?: string) {
  return {
    id,
    timestamp: at(offsetMs),
    level,
    message,
    source,
  };
}

export function createMockExecutionTrace({
  incidentKey = "payment-api / elevated p95 latency",
  investigationId = "inv_payment_api_042",
  runId = "run_20260313_102500_9af3",
}: {
  incidentKey?: string;
  investigationId?: string;
  runId?: string;
} = {}): ExecutionRunTrace {
  return {
    runId,
    previousRunId: "run_20260313_094112_771e",
    title: `${incidentKey} · Execution Mapper`,
    workflowTitle: "Agentic RCA Workflow",
    environment: "prod-us-east-1",
    status: "failed",
    startedAt: at(0),
    endedAt: at(23350),
    durationMs: 23350,
    currentEventId: "evt-jira-attempt-2",
    compare: {
      durationDeltaMs: 5140,
      costDeltaUsd: 0.12,
      tokenDelta: 816,
      regressionNodeIds: ["collect_evidence", "publish_report", "jira_publish"],
    },
    groups: [
      {
        id: "group-orchestration",
        label: "Orchestration",
        x: 20,
        y: 36,
        width: 800,
        height: 250,
        tone: "neutral",
      },
      {
        id: "group-evidence",
        label: "Evidence Fanout",
        x: 840,
        y: 36,
        width: 700,
        height: 500,
        tone: "accent",
      },
      {
        id: "group-delivery",
        label: "Authoring + Delivery",
        x: 1560,
        y: 36,
        width: 620,
        height: 500,
        tone: "danger",
      },
    ],
    nodes: [
      {
        id: "alert_trigger",
        label: "Alert Trigger",
        kind: "trigger",
        state: "success",
        x: 70,
        y: 104,
        durationMs: 280,
        retryCount: 0,
        itemCount: 1,
        summary: "PagerDuty incident ingested and normalized into an RCA run payload.",
        inputSummary: "PagerDuty v2 incident payload",
        outputSummary: "Normalized alert context with service hints",
        eventIds: ["evt-alert"],
        upstream: [],
        downstream: ["resolve_service_identity"],
      },
      {
        id: "resolve_service_identity",
        label: "Resolve Service Identity",
        kind: "stage",
        state: "success",
        x: 320,
        y: 104,
        durationMs: 1820,
        tokenCount: 228,
        costUsd: 0.002,
        retryCount: 0,
        itemCount: 4,
        summary: "Mapped provider aliases to the canonical payment-api service and blast radius.",
        inputSummary: "Alert labels, traces, prior incident context",
        outputSummary: "Canonical service + environment + dependency edges",
        eventIds: ["evt-resolve", "evt-resolve-alias"],
        upstream: ["alert_trigger"],
        downstream: ["build_investigation_plan"],
      },
      {
        id: "build_investigation_plan",
        label: "Build Investigation Plan",
        kind: "stage",
        state: "success",
        x: 570,
        y: 104,
        durationMs: 1490,
        tokenCount: 312,
        costUsd: 0.004,
        retryCount: 0,
        itemCount: 6,
        summary: "Selected bounded telemetry queries and prioritised evidence fanout.",
        inputSummary: "Resolved service, prior context pack, investigation heuristics",
        outputSummary: "Fanout plan across traces, metrics, and retrieval",
        eventIds: ["evt-plan"],
        upstream: ["resolve_service_identity"],
        downstream: ["collect_evidence"],
      },
      {
        id: "collect_evidence",
        label: "Collect Evidence",
        kind: "stage",
        state: "warning",
        x: 870,
        y: 104,
        durationMs: 9430,
        tokenCount: 0,
        costUsd: 0,
        retryCount: 1,
        itemCount: 18,
        summary: "Fetched metrics, trace summaries, and context documents; one trace query required retry.",
        inputSummary: "Investigation plan with 3 parallel tasks",
        outputSummary: "Evidence bundle with latency, error rate, and deployment context",
        eventIds: [
          "evt-collect",
          "evt-prometheus",
          "evt-tempo-attempt-1",
          "evt-tempo-retry",
          "evt-tempo-attempt-2",
          "evt-context-retrieval",
        ],
        upstream: ["build_investigation_plan"],
        downstream: ["synthesize_rca_report"],
      },
      {
        id: "prometheus_query",
        label: "Prometheus Query",
        kind: "tool",
        state: "success",
        x: 840,
        y: 338,
        durationMs: 2260,
        retryCount: 0,
        itemCount: 5,
        summary: "Pulled p50, p95, error-rate, and saturation metrics for payment-api.",
        inputSummary: "PromQL bundle across 15m and 60m windows",
        outputSummary: "Latency and saturation time series",
        eventIds: ["evt-prometheus"],
        upstream: ["collect_evidence"],
        downstream: ["synthesize_rca_report"],
        tool: "prometheus.query_range",
      },
      {
        id: "tempo_trace_query",
        label: "Tempo Trace Drilldown",
        kind: "tool",
        state: "success",
        x: 1090,
        y: 338,
        durationMs: 3610,
        retryCount: 1,
        itemCount: 3,
        summary: "Initial trace search timed out; retry with narrowed service.operation filter succeeded.",
        inputSummary: "Tempo search by service and exemplar trace IDs",
        outputSummary: "Top slow spans for checkout and risk evaluation",
        eventIds: ["evt-tempo-attempt-1", "evt-tempo-retry", "evt-tempo-attempt-2"],
        upstream: ["collect_evidence"],
        downstream: ["synthesize_rca_report"],
        tool: "tempo.search_traces",
      },
      {
        id: "context_retrieval",
        label: "Context Retrieval",
        kind: "retrieval",
        state: "success",
        x: 1320,
        y: 338,
        durationMs: 1290,
        tokenCount: 0,
        costUsd: 0,
        retryCount: 0,
        itemCount: 7,
        summary: "Retrieved prior incidents, runbook steps, and recent rollout notes from the context pack.",
        inputSummary: "Service tags, deployment markers, historical incidents",
        outputSummary: "7 context chunks ranked by recency and relevance",
        eventIds: ["evt-context-retrieval"],
        upstream: ["collect_evidence"],
        downstream: ["synthesize_rca_report"],
        tool: "context.search",
      },
      {
        id: "synthesize_rca_report",
        label: "Synthesize RCA Report",
        kind: "stage",
        state: "success",
        x: 1250,
        y: 104,
        durationMs: 5740,
        tokenCount: 4168,
        costUsd: 0.112,
        retryCount: 0,
        itemCount: 11,
        summary: "Composed the RCA narrative and recommendations from evidence and retrieval context.",
        inputSummary: "Evidence bundle + retrieved runbooks + prior incident context",
        outputSummary: "RCA draft with root cause, blast radius, and follow-up actions",
        eventIds: ["evt-synthesize", "evt-gpt5-call", "evt-stream-1", "evt-stream-2", "evt-stream-3"],
        upstream: ["collect_evidence", "prometheus_query", "tempo_trace_query", "context_retrieval"],
        downstream: ["publish_report"],
      },
      {
        id: "gpt5_rca_model",
        label: "GPT-5 RCA Synthesis",
        kind: "model",
        state: "success",
        x: 1310,
        y: 338,
        durationMs: 4320,
        tokenCount: 4168,
        costUsd: 0.112,
        retryCount: 0,
        itemCount: 3,
        summary: "Generated hypothesis ranking, contradictions, and a concise remediation memo.",
        inputSummary: "Structured evidence bundle and retrieval excerpts",
        outputSummary: "Streamed RCA draft",
        eventIds: ["evt-gpt5-call", "evt-stream-1", "evt-stream-2", "evt-stream-3"],
        upstream: ["synthesize_rca_report"],
        downstream: ["publish_report"],
        model: "gpt-5.4",
      },
      {
        id: "publish_report",
        label: "Publish Report",
        kind: "stage",
        state: "failed",
        x: 1600,
        y: 104,
        durationMs: 4590,
        retryCount: 2,
        itemCount: 4,
        summary: "Slack publication succeeded, but Jira issue update failed twice due to a stale transition ID.",
        inputSummary: "RCA report and follow-up tasks",
        outputSummary: "Slack posted; Jira transition blocked",
        eventIds: ["evt-publish", "evt-slack-publish", "evt-jira-attempt-1", "evt-jira-retry", "evt-jira-attempt-2"],
        upstream: ["synthesize_rca_report", "gpt5_rca_model"],
        downstream: ["emit_eval_event"],
      },
      {
        id: "slack_publish",
        label: "Slack Publish",
        kind: "tool",
        state: "success",
        x: 1560,
        y: 338,
        durationMs: 540,
        retryCount: 0,
        itemCount: 1,
        summary: "Posted RCA summary into #incident-rca with citations and owners.",
        inputSummary: "Markdown report card",
        outputSummary: "Slack permalink",
        eventIds: ["evt-slack-publish"],
        upstream: ["publish_report"],
        downstream: [],
        tool: "slack.chat_postMessage",
      },
      {
        id: "jira_publish",
        label: "Jira Transition",
        kind: "tool",
        state: "failed",
        x: 1820,
        y: 338,
        durationMs: 2610,
        retryCount: 2,
        itemCount: 2,
        summary: "Jira issue transition could not resolve the expected workflow state after rollout changes.",
        inputSummary: "Issue key + transition payload",
        outputSummary: "HTTP 400 validation error",
        eventIds: ["evt-jira-attempt-1", "evt-jira-retry", "evt-jira-attempt-2"],
        upstream: ["publish_report"],
        downstream: ["emit_eval_event"],
        tool: "jira.transition_issue",
      },
      {
        id: "emit_eval_event",
        label: "Emit Eval Event",
        kind: "evaluation",
        state: "skipped",
        x: 1900,
        y: 104,
        durationMs: 0,
        retryCount: 0,
        itemCount: 0,
        summary: "Evaluation event was skipped because the delivery stage did not complete successfully.",
        inputSummary: "Run metadata and RCA outcome",
        outputSummary: "Skipped due to upstream failure",
        eventIds: ["evt-emit-eval"],
        upstream: ["publish_report", "jira_publish"],
        downstream: [],
      },
    ],
    edges: [
      { id: "edge-alert-resolve", source: "alert_trigger", target: "resolve_service_identity", state: "active", animated: true, relation: "primary" },
      { id: "edge-resolve-plan", source: "resolve_service_identity", target: "build_investigation_plan", state: "active", animated: true, relation: "primary" },
      { id: "edge-plan-collect", source: "build_investigation_plan", target: "collect_evidence", state: "active", animated: true, relation: "primary" },
      { id: "edge-collect-prom", source: "collect_evidence", target: "prometheus_query", state: "active", animated: true, label: "metrics", relation: "fanout" },
      { id: "edge-collect-tempo", source: "collect_evidence", target: "tempo_trace_query", state: "active", animated: true, label: "traces", relation: "fanout" },
      { id: "edge-collect-context", source: "collect_evidence", target: "context_retrieval", state: "active", animated: true, label: "retrieval", relation: "fanout" },
      { id: "edge-prom-synth", source: "prometheus_query", target: "synthesize_rca_report", state: "active", animated: false, relation: "primary" },
      { id: "edge-tempo-synth", source: "tempo_trace_query", target: "synthesize_rca_report", state: "active", animated: false, relation: "primary" },
      { id: "edge-context-synth", source: "context_retrieval", target: "synthesize_rca_report", state: "active", animated: false, relation: "primary" },
      { id: "edge-synth-model", source: "synthesize_rca_report", target: "gpt5_rca_model", state: "active", animated: true, label: "model", relation: "model" },
      { id: "edge-model-publish", source: "gpt5_rca_model", target: "publish_report", state: "active", animated: false, relation: "primary" },
      { id: "edge-publish-slack", source: "publish_report", target: "slack_publish", state: "active", animated: false, label: "slack", relation: "publish" },
      { id: "edge-publish-jira", source: "publish_report", target: "jira_publish", state: "failed", animated: true, label: "retry x2", relation: "retry" },
      { id: "edge-publish-eval", source: "publish_report", target: "emit_eval_event", state: "skipped", animated: false, relation: "primary" },
      { id: "edge-jira-eval", source: "jira_publish", target: "emit_eval_event", state: "skipped", animated: false, relation: "primary" },
    ],
    events: [
      {
        id: "evt-alert",
        nodeId: "alert_trigger",
        childEventIds: [],
        title: "Ingest incident trigger",
        description: "PagerDuty webhook was parsed and normalized into a workflow payload.",
        kind: "stage",
        status: "success",
        startedAt: at(0),
        endedAt: at(280),
        durationMs: 280,
        input: {
          source: "pagerduty",
          incident_key: "PD-17344",
          service_hint: "payment-api",
          severity: "critical",
        },
        output: {
          incident_id: investigationId,
          canonical_service_hint: "payment-api",
          routing_environment: "prod-us-east-1",
        },
        raw: {
          trigger: "incident.created",
          payload_version: "v2",
        },
        logs: [
          log("log-alert-1", 40, "info", "PagerDuty incident payload received", "trigger"),
          log("log-alert-2", 210, "info", "Workflow run created and queued", "orchestrator"),
        ],
        metrics: {
          queueMs: 0,
          executionMs: 280,
          itemCount: 1,
        },
        tags: ["user-visible", "trigger"],
        rootEventId: "evt-alert",
      },
      {
        id: "evt-resolve",
        nodeId: "resolve_service_identity",
        childEventIds: ["evt-resolve-alias"],
        title: "Resolve canonical service",
        description: "Linked incident aliases, dependency edges, and prior RCA context to the canonical service identity.",
        kind: "stage",
        status: "success",
        startedAt: at(320),
        endedAt: at(2140),
        durationMs: 1820,
        input: {
          service_candidates: ["payment-api", "checkout-gateway", "pay-api"],
          trace_ids: ["87fab7db5e2a1d53"],
          metric_labels: { app: "payment-api", namespace: "payments" },
        },
        output: {
          resolved_service: "payment-api",
          owner_team: "payments-platform",
          downstream_dependencies: ["risk-engine", "ledger-writer"],
        },
        raw: {
          classifier: "service-identity-resolver",
          confidence: 0.97,
        },
        logs: [
          log("log-resolve-1", 440, "info", "Loaded service alias catalog", "resolver"),
          log("log-resolve-2", 1290, "info", "Matched trace exemplar to payment-api", "resolver"),
          log("log-resolve-3", 1980, "debug", "Resolved blast radius edges: 2", "resolver"),
        ],
        metrics: {
          queueMs: 22,
          executionMs: 1798,
          tokenInput: 114,
          tokenOutput: 114,
          costUsd: 0.002,
          itemCount: 4,
          latencySeries: [280, 310, 260, 380, 410, 258],
        },
        model: "gpt-5.4-mini",
        tags: ["stage"],
        rootEventId: "evt-resolve",
      },
      {
        id: "evt-resolve-alias",
        nodeId: "resolve_service_identity",
        parentEventId: "evt-resolve",
        childEventIds: [],
        title: "Resolve alias conflicts",
        description: "Scored conflicting aliases using trace and namespace context.",
        kind: "transform",
        status: "success",
        startedAt: at(980),
        endedAt: at(1450),
        durationMs: 470,
        input: {
          alias_candidates: ["payment-api", "pay-api"],
          evidence: ["trace.service.name", "kubernetes.namespace"],
        },
        output: {
          selected_alias: "payment-api",
          confidence: 0.97,
        },
        raw: {
          arbitration_mode: "weighted",
        },
        logs: [log("log-resolve-alias-1", 1120, "info", "Alias arbitration completed", "resolver")],
        metrics: {
          executionMs: 470,
        },
        tags: ["internal"],
        rootEventId: "evt-resolve",
      },
      {
        id: "evt-plan",
        nodeId: "build_investigation_plan",
        childEventIds: [],
        title: "Build bounded investigation plan",
        description: "Selected evidence fanout strategy with query limits and fallback paths.",
        kind: "stage",
        status: "success",
        startedAt: at(2200),
        endedAt: at(3690),
        durationMs: 1490,
        input: {
          service: "payment-api",
          incident_severity: "critical",
          objective: "Explain p95 latency spike and failed checkout transactions",
        },
        output: {
          plan: [
            "query prometheus for p95/error/saturation",
            "drill into exemplar traces",
            "retrieve recent rollout notes",
          ],
          max_parallel_calls: 3,
        },
        raw: {
          planner: "bounded-evidence-v2",
        },
        logs: [
          log("log-plan-1", 2440, "info", "Evidence fanout planned with 3 parallel tasks", "planner"),
          log("log-plan-2", 3310, "debug", "Added retry budget for trace store", "planner"),
        ],
        metrics: {
          queueMs: 18,
          executionMs: 1472,
          tokenInput: 148,
          tokenOutput: 164,
          costUsd: 0.004,
          itemCount: 6,
          latencySeries: [180, 194, 236, 310, 290, 262],
        },
        model: "gpt-5.4-mini",
        tags: ["stage"],
        rootEventId: "evt-plan",
      },
      {
        id: "evt-collect",
        nodeId: "collect_evidence",
        childEventIds: ["evt-prometheus", "evt-tempo-attempt-1", "evt-tempo-retry", "evt-tempo-attempt-2", "evt-context-retrieval"],
        title: "Collect evidence fanout",
        description: "Executed parallel telemetry collection and retrieval plan. Trace search required retry after a timeout.",
        kind: "stage",
        status: "warning",
        startedAt: at(3820),
        endedAt: at(13250),
        durationMs: 9430,
        input: {
          task_count: 3,
          retries_allowed: 1,
        },
        output: {
          evidence_count: 18,
          trace_retry_count: 1,
          ready_for_synthesis: true,
        },
        raw: {
          parallel_branches: ["metrics", "traces", "retrieval"],
        },
        logs: [
          log("log-collect-1", 3900, "info", "Parallel evidence fanout started", "collector"),
          log("log-collect-2", 7210, "warn", "Trace search exceeded timeout budget; scheduling retry", "collector"),
          log("log-collect-3", 12890, "info", "Evidence bundle finalized", "collector"),
        ],
        metrics: {
          queueMs: 40,
          executionMs: 9390,
          networkMs: 7180,
          toolMs: 7160,
          itemCount: 18,
          latencySeries: [1200, 980, 1430, 760, 1360, 1650, 1010],
        },
        tags: ["stage"],
        rootEventId: "evt-collect",
      },
      {
        id: "evt-prometheus",
        nodeId: "prometheus_query",
        parentEventId: "evt-collect",
        childEventIds: [],
        title: "Query Prometheus ranges",
        description: "Fetched latency, error, and saturation series for payment-api.",
        kind: "tool_call",
        status: "success",
        startedAt: at(3980),
        endedAt: at(6240),
        durationMs: 2260,
        input: {
          queries: [
            "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{service='payment-api'}[5m])) by (le))",
            "sum(rate(http_requests_total{service='payment-api',status=~'5..'}[5m]))",
            "sum(container_cpu_usage_seconds_total{pod=~'payment-api-.*'})",
          ],
        },
        output: {
          series_count: 5,
          p95_peak_ms: 3240,
          error_rate_peak: 0.042,
        },
        raw: {
          tool: "prometheus.query_range",
          datasource: "prod-metrics",
        },
        logs: [
          log("log-prom-1", 4120, "info", "Prometheus query bundle dispatched", "prometheus"),
          log("log-prom-2", 6110, "info", "Prometheus result set normalized", "prometheus"),
        ],
        metrics: {
          executionMs: 2260,
          networkMs: 1980,
          toolMs: 2260,
          itemCount: 5,
          latencySeries: [310, 430, 470, 520, 530],
        },
        tool: "prometheus.query_range",
        tags: ["tool"],
        rootEventId: "evt-collect",
      },
      {
        id: "evt-tempo-attempt-1",
        nodeId: "tempo_trace_query",
        parentEventId: "evt-collect",
        childEventIds: [],
        title: "Search traces (attempt 1)",
        description: "Wide trace search against Tempo timed out before the result budget was satisfied.",
        kind: "tool_call",
        status: "failed",
        startedAt: at(4210),
        endedAt: at(6670),
        durationMs: 2460,
        input: {
          service: "payment-api",
          limit: 50,
          lookback_minutes: 30,
        },
        output: {
          partial_matches: 7,
        },
        raw: {
          tool: "tempo.search_traces",
          timeout_ms: 2400,
        },
        logs: [
          log("log-tempo-1", 4450, "info", "Tempo search started", "tempo"),
          log("log-tempo-2", 6630, "error", "Tempo search timed out after 2400ms", "tempo"),
        ],
        metrics: {
          executionMs: 2460,
          networkMs: 2400,
          toolMs: 2460,
          itemCount: 1,
        },
        tool: "tempo.search_traces",
        error: {
          summary: "Trace search timed out",
          message: "Tempo search exceeded the 2400ms timeout budget before the 50-trace limit was satisfied.",
          stack: [
            "TimeoutError: upstream search timed out",
            "at TempoClient.searchTraces (trace.ts:184:11)",
            "at retryableToolCall (tools.ts:73:5)",
          ],
          rootCauseHints: [
            "The search window was broader than the current timeout budget.",
            "Narrowing the operation filter or reducing result count should succeed.",
          ],
          relatedEventIds: ["evt-tempo-retry", "evt-tempo-attempt-2"],
        },
        tags: ["tool", "error"],
        retryIndex: 0,
        rootEventId: "evt-collect",
      },
      {
        id: "evt-tempo-retry",
        nodeId: "tempo_trace_query",
        parentEventId: "evt-collect",
        childEventIds: [],
        title: "Retry trace search with narrower filter",
        description: "Retry scheduler reduced the search window and applied operation-level filtering.",
        kind: "retry",
        status: "retrying",
        startedAt: at(6750),
        endedAt: at(7140),
        durationMs: 390,
        input: {
          prior_timeout_ms: 2400,
          strategy: "narrow_window_and_filter_operation",
        },
        output: {
          next_timeout_ms: 2800,
          next_limit: 20,
          operation_filter: "POST /checkout",
        },
        raw: {
          retry_policy: "tool-default",
        },
        logs: [log("log-tempo-retry-1", 6840, "warn", "Applying retry strategy: narrow window and lower result count", "retry")],
        metrics: {
          executionMs: 390,
        },
        retryIndex: 1,
        tags: ["retry"],
        rootEventId: "evt-collect",
      },
      {
        id: "evt-tempo-attempt-2",
        nodeId: "tempo_trace_query",
        parentEventId: "evt-collect",
        childEventIds: [],
        title: "Search traces (attempt 2)",
        description: "Retry succeeded with a narrowed operation filter and returned the top slow spans.",
        kind: "tool_call",
        status: "success",
        startedAt: at(7190),
        endedAt: at(9070),
        durationMs: 1880,
        input: {
          service: "payment-api",
          operation: "POST /checkout",
          limit: 20,
          lookback_minutes: 10,
        },
        output: {
          traces_returned: 12,
          top_span: "risk-engine.score",
          top_span_latency_ms: 1884,
        },
        raw: {
          tool: "tempo.search_traces",
          timeout_ms: 2800,
        },
        logs: [
          log("log-tempo-3", 7320, "info", "Retry trace search started", "tempo"),
          log("log-tempo-4", 9030, "info", "Slow span summary extracted", "tempo"),
        ],
        metrics: {
          executionMs: 1880,
          networkMs: 1810,
          toolMs: 1880,
          itemCount: 3,
          latencySeries: [360, 380, 420, 350, 370],
        },
        tool: "tempo.search_traces",
        retryIndex: 1,
        tags: ["tool", "retry"],
        rootEventId: "evt-collect",
      },
      {
        id: "evt-context-retrieval",
        nodeId: "context_retrieval",
        parentEventId: "evt-collect",
        childEventIds: [],
        title: "Retrieve prior incident context",
        description: "Loaded runbook steps and prior incident notes relevant to recent checkout latency regressions.",
        kind: "retrieval",
        status: "success",
        startedAt: at(4300),
        endedAt: at(5590),
        durationMs: 1290,
        input: {
          query: "payment-api checkout latency deployment rollback warm pool",
          top_k: 7,
        },
        output: {
          chunks: 7,
          top_source: "runbook/payment-api-cold-start.md",
        },
        raw: {
          tool: "context.search",
          corpus: "operational-context",
        },
        logs: [
          log("log-context-1", 4420, "info", "Context retrieval query dispatched", "retrieval"),
          log("log-context-2", 5510, "info", "Retrieved 7 ranked context chunks", "retrieval"),
        ],
        metrics: {
          executionMs: 1290,
          networkMs: 980,
          itemCount: 7,
          latencySeries: [190, 210, 180, 160, 205],
        },
        tool: "context.search",
        tags: ["retrieval"],
        rootEventId: "evt-collect",
      },
      {
        id: "evt-synthesize",
        nodeId: "synthesize_rca_report",
        childEventIds: ["evt-gpt5-call"],
        title: "Synthesize RCA report",
        description: "Merged evidence and retrieval context into a ranked root-cause narrative with action items.",
        kind: "stage",
        status: "success",
        startedAt: at(13400),
        endedAt: at(19140),
        durationMs: 5740,
        input: {
          evidence_bundle: {
            metric_anomalies: 3,
            trace_clusters: 2,
            retrieval_chunks: 7,
          },
          objective: "Explain p95 latency spike and failed checkouts",
        },
        output: {
          likely_cause: "Warm-pool exhaustion increased synchronous risk-engine calls during a rollout.",
          confidence: 0.84,
          recommended_actions: [
            "Increase warm pool size for payment-api",
            "Throttle risk-engine fanout during rollout windows",
            "Invalidate stale Jira workflow transition map",
          ],
        },
        raw: {
          synthesis_mode: "contradiction-aware",
        },
        logs: [
          log("log-synth-1", 13620, "info", "Evidence bundle passed validation", "synthesizer"),
          log("log-synth-2", 18980, "info", "RCA draft generated", "synthesizer"),
        ],
        metrics: {
          queueMs: 50,
          executionMs: 5690,
          modelMs: 4320,
          tokenInput: 2954,
          tokenOutput: 1214,
          costUsd: 0.112,
          itemCount: 11,
          latencySeries: [460, 480, 520, 610, 700, 690, 610],
        },
        model: "gpt-5.4",
        tags: ["stage"],
        rootEventId: "evt-synthesize",
      },
      {
        id: "evt-gpt5-call",
        nodeId: "gpt5_rca_model",
        parentEventId: "evt-synthesize",
        childEventIds: ["evt-stream-1", "evt-stream-2", "evt-stream-3"],
        title: "Call GPT-5.4 for synthesis",
        description: "Model generated the RCA narrative as a streamed response with contradiction checks.",
        kind: "model_call",
        status: "success",
        startedAt: at(13920),
        endedAt: at(18240),
        durationMs: 4320,
        input: {
          model: "gpt-5.4",
          temperature: 0.1,
          messages: 6,
          system_goal: "Produce a concise but evidence-backed RCA.",
        },
        output: {
          finish_reason: "stop",
          contradictions_found: 1,
          final_sections: ["Likely cause", "Blast radius", "Actions"],
        },
        raw: {
          model: "gpt-5.4",
          response_id: "resp_8f2c1c",
        },
        logs: [
          log("log-gpt-1", 14080, "info", "Model request accepted", "openai"),
          log("log-gpt-2", 18120, "info", "Streaming completed with stop finish_reason", "openai"),
        ],
        metrics: {
          executionMs: 4320,
          modelMs: 4320,
          tokenInput: 2954,
          tokenOutput: 1214,
          costUsd: 0.112,
          latencySeries: [530, 540, 612, 670, 720, 620, 628],
        },
        stream: {
          preview: "Likely cause: payment-api exhausted its warm worker pool during rollout, increasing synchronous calls to risk-engine...",
          truncated: true,
          chunks: [
            {
              id: "chunk-1",
              timestamp: at(15100),
              text: "Likely cause: payment-api exhausted its warm worker pool during rollout, increasing synchronous risk-engine calls.",
            },
            {
              id: "chunk-2",
              timestamp: at(16340),
              text: "Evidence: p95 latency spiked to 3.24s, error rate reached 4.2%, and trace data shows risk-engine.score spans dominating checkout.",
            },
            {
              id: "chunk-3",
              timestamp: at(17880),
              text: "Recommended actions: scale warm pool, gate rollout fanout, and update Jira transition mapping to restore incident delivery.",
            },
          ],
        },
        model: "gpt-5.4",
        tags: ["model", "user-visible"],
        rootEventId: "evt-synthesize",
      },
      {
        id: "evt-stream-1",
        nodeId: "gpt5_rca_model",
        parentEventId: "evt-gpt5-call",
        childEventIds: [],
        title: "Stream chunk 1",
        description: "Model emitted likely cause summary.",
        kind: "stream",
        status: "success",
        startedAt: at(15080),
        endedAt: at(15160),
        durationMs: 80,
        input: null,
        output: "Likely cause: payment-api exhausted its warm worker pool during rollout...",
        raw: {
          delta_index: 1,
        },
        logs: [],
        metrics: {
          executionMs: 80,
        },
        tags: ["stream"],
        rootEventId: "evt-synthesize",
      },
      {
        id: "evt-stream-2",
        nodeId: "gpt5_rca_model",
        parentEventId: "evt-gpt5-call",
        childEventIds: [],
        title: "Stream chunk 2",
        description: "Model emitted evidence summary.",
        kind: "stream",
        status: "success",
        startedAt: at(16320),
        endedAt: at(16400),
        durationMs: 80,
        input: null,
        output: "Evidence: p95 latency spiked to 3.24s and trace data shows risk-engine.score dominating checkout.",
        raw: {
          delta_index: 2,
        },
        logs: [],
        metrics: {
          executionMs: 80,
        },
        tags: ["stream"],
        rootEventId: "evt-synthesize",
      },
      {
        id: "evt-stream-3",
        nodeId: "gpt5_rca_model",
        parentEventId: "evt-gpt5-call",
        childEventIds: [],
        title: "Stream chunk 3",
        description: "Model emitted remediation plan.",
        kind: "stream",
        status: "success",
        startedAt: at(17860),
        endedAt: at(17940),
        durationMs: 80,
        input: null,
        output: "Recommended actions: scale warm pool, gate rollout fanout, and update Jira transition mapping.",
        raw: {
          delta_index: 3,
        },
        logs: [],
        metrics: {
          executionMs: 80,
        },
        tags: ["stream"],
        rootEventId: "evt-synthesize",
      },
      {
        id: "evt-publish",
        nodeId: "publish_report",
        childEventIds: ["evt-slack-publish", "evt-jira-attempt-1", "evt-jira-retry", "evt-jira-attempt-2"],
        title: "Publish RCA outputs",
        description: "Delivery fanout attempted Slack and Jira publication. Slack succeeded; Jira failed twice.",
        kind: "publish",
        status: "failed",
        startedAt: at(19210),
        endedAt: at(23800),
        durationMs: 4590,
        input: {
          destinations: ["slack", "jira"],
          incident_key: "INC-4421",
        },
        output: {
          slack: "success",
          jira: "failed",
        },
        raw: {
          delivery_mode: "fanout",
        },
        logs: [
          log("log-publish-1", 19320, "info", "Slack delivery started", "delivery"),
          log("log-publish-2", 19910, "info", "Slack delivery completed", "delivery"),
          log("log-publish-3", 20820, "error", "Jira transition failed; retry scheduled", "delivery"),
          log("log-publish-4", 23680, "error", "Jira transition failed after retry budget exhausted", "delivery"),
        ],
        metrics: {
          executionMs: 4590,
          networkMs: 3130,
          toolMs: 3150,
          itemCount: 4,
          latencySeries: [320, 540, 690, 840, 1210, 990],
        },
        tags: ["stage", "error", "user-visible"],
        rootEventId: "evt-publish",
      },
      {
        id: "evt-slack-publish",
        nodeId: "slack_publish",
        parentEventId: "evt-publish",
        childEventIds: [],
        title: "Post RCA to Slack",
        description: "Posted the summary card with citations into the incident room.",
        kind: "tool_call",
        status: "success",
        startedAt: at(19360),
        endedAt: at(19900),
        durationMs: 540,
        input: {
          channel: "#incident-rca",
          blocks: 7,
        },
        output: {
          permalink: "https://slack.example.com/archives/C123/p123456789",
        },
        raw: {
          tool: "slack.chat_postMessage",
        },
        logs: [log("log-slack-1", 19860, "info", "Slack message acknowledged", "slack")],
        metrics: {
          executionMs: 540,
          networkMs: 500,
          toolMs: 540,
          itemCount: 1,
        },
        tool: "slack.chat_postMessage",
        tags: ["tool", "user-visible"],
        rootEventId: "evt-publish",
      },
      {
        id: "evt-jira-attempt-1",
        nodeId: "jira_publish",
        parentEventId: "evt-publish",
        childEventIds: [],
        title: "Transition Jira issue (attempt 1)",
        description: "Jira transition payload referenced a stale workflow transition ID after a recent config change.",
        kind: "tool_call",
        status: "failed",
        startedAt: at(20180),
        endedAt: at(21410),
        durationMs: 1230,
        input: {
          issue_key: "INC-4421",
          transition_id: "41",
        },
        output: {
          http_status: 400,
          error_code: "INVALID_TRANSITION",
        },
        raw: {
          tool: "jira.transition_issue",
          response_body: {
            errors: ["Transition id 41 is not valid for the current workflow state"],
          },
        },
        logs: [
          log("log-jira-1", 20380, "info", "Jira transition request sent", "jira"),
          log("log-jira-2", 21380, "error", "Jira rejected transition id 41", "jira"),
        ],
        metrics: {
          executionMs: 1230,
          networkMs: 1180,
          toolMs: 1230,
        },
        tool: "jira.transition_issue",
        error: {
          summary: "Jira transition rejected",
          message: "Transition id 41 is no longer valid for issue INC-4421 after the workflow rollout.",
          stack: [
            "JiraHttpError: HTTP 400 INVALID_TRANSITION",
            "at JiraClient.transitionIssue (jira.ts:207:13)",
            "at publishReport (delivery.ts:114:7)",
          ],
          rootCauseHints: [
            "The incident workflow mapping appears stale relative to the current Jira workflow.",
            "Refreshing transition metadata before publish would avoid this class of failure.",
          ],
          relatedEventIds: ["evt-jira-retry", "evt-jira-attempt-2"],
        },
        retryIndex: 0,
        tags: ["tool", "error"],
        rootEventId: "evt-publish",
      },
      {
        id: "evt-jira-retry",
        nodeId: "jira_publish",
        parentEventId: "evt-publish",
        childEventIds: [],
        title: "Retry Jira transition with fresh metadata",
        description: "Refresh attempt fetched workflow metadata, but the transition remained unmapped.",
        kind: "retry",
        status: "retrying",
        startedAt: at(21480),
        endedAt: at(22010),
        durationMs: 530,
        input: {
          strategy: "refresh_transition_metadata",
        },
        output: {
          transitions_found: ["18", "22", "49"],
          mapped_transition: null,
        },
        raw: {
          retry_policy: "delivery-default",
        },
        logs: [log("log-jira-retry-1", 21830, "warn", "Unable to map desired resolved state after metadata refresh", "jira")],
        metrics: {
          executionMs: 530,
        },
        retryIndex: 1,
        tags: ["retry", "error"],
        rootEventId: "evt-publish",
      },
      {
        id: "evt-jira-attempt-2",
        nodeId: "jira_publish",
        parentEventId: "evt-publish",
        childEventIds: [],
        title: "Transition Jira issue (attempt 2)",
        description: "Second attempt failed because the desired delivery transition could not be inferred safely.",
        kind: "tool_call",
        status: "failed",
        startedAt: at(22110),
        endedAt: at(23800),
        durationMs: 1690,
        input: {
          issue_key: "INC-4421",
          candidate_transitions: ["18", "22", "49"],
        },
        output: {
          http_status: 400,
          error_code: "UNMAPPED_STATE",
        },
        raw: {
          tool: "jira.transition_issue",
          response_body: {
            errors: ["Unable to infer target workflow state from requested action"],
          },
        },
        logs: [
          log("log-jira-3", 22310, "info", "Retry Jira transition request sent", "jira"),
          log("log-jira-4", 23740, "error", "Retry failed: target workflow state unmapped", "jira"),
        ],
        metrics: {
          executionMs: 1690,
          networkMs: 1580,
          toolMs: 1690,
        },
        tool: "jira.transition_issue",
        error: {
          summary: "Jira workflow state unmapped",
          message: "The delivery workflow could not infer a safe transition for the current Jira project configuration.",
          stack: [
            "DeliveryInvariantError: desired resolved state missing transition mapping",
            "at mapTargetTransition (delivery.ts:82:15)",
            "at publishReport (delivery.ts:118:5)",
          ],
          rootCauseHints: [
            "This failure is downstream of a configuration mismatch rather than evidence or synthesis quality.",
            "Refreshing the Jira workflow mapping or falling back to comment-only delivery would recover the run.",
          ],
          relatedEventIds: ["evt-publish", "evt-emit-eval"],
        },
        retryIndex: 1,
        tags: ["tool", "error", "user-visible"],
        rootEventId: "evt-publish",
      },
      {
        id: "evt-emit-eval",
        nodeId: "emit_eval_event",
        childEventIds: [],
        title: "Skip evaluation emission",
        description: "Evaluation event emission was skipped because the delivery stage did not complete.",
        kind: "branch",
        status: "skipped",
        startedAt: at(23810),
        endedAt: at(23820),
        durationMs: 10,
        input: {
          upstream_status: "failed",
        },
        output: {
          skipped_reason: "delivery_incomplete",
        },
        raw: {
          rule: "emit_only_if_publish_succeeds",
        },
        logs: [log("log-eval-1", 23812, "info", "Evaluation event skipped", "evaluation")],
        metrics: {
          executionMs: 10,
        },
        tags: ["skipped"],
        rootEventId: "evt-emit-eval",
      },
    ],
  };
}
