apiVersion: v1
kind: Service
metadata:
  name: {{ include "rca-platform.fullname" . }}-ingest-api
spec:
  selector:
    app: {{ include "rca-platform.fullname" . }}-ingest-api
  ports:
    - port: {{ .Values.ingestApi.port }}
      targetPort: {{ .Values.ingestApi.port }}
      protocol: TCP
