apiVersion: v1
kind: Service
metadata:
  name: {{ include "rca-platform.fullname" . }}-web-ui
spec:
  selector:
    app: {{ include "rca-platform.fullname" . }}-web-ui
  ports:
    - port: {{ .Values.webUi.port }}
      targetPort: {{ .Values.webUi.port }}
      protocol: TCP
